### ISSUE TITLE
Update README with info on how to properly use the API key.

### ISSUE THREAD

**Issue by jaredwhanisch** [joe-studer-18/mst-ka-site#110]
I accidentally pushed the API key. It'd be sweet if we had some step by step instructions included in the README of how to properly format *firebase-init.js* to work with the API key in the future.

**Comment by joe-studer-18** [comment]
Tbh I dont entirely remember how to get the key - where'd you snag it again?

**Comment by jaredwhanisch** [comment]
Firebase console > mst-ka > 2 apps > alumni-auth (click the gear) > SDK setup and configuration
Then I just put the `var firebaseConfig{}` into the firebase-init.js file on my local machine.
