### ISSUE TITLE
Update pictures throughout the website

### ISSUE THREAD

**Issue by jaredwhanisch** [joe-studer-18/mst-ka-site#149]
A lot of the pictures are old and low quality, especially in the About, Values, and Awards pages.  The pages: _/values_ & _/values/top-5-reasons_ need pictures, make it look similar to the _/about_ page.

Take some time to organize with the V(Historian) or someone with the chapter that can provide new images to replace the existing ones.

**Comment by developer-irfan** [comment]
hello @jaredwhanisch assign me this i will update images with new ones

**Comment by jaredwhanisch** [comment]
@developer-irfan Have at it!

**Comment by jaredwhanisch** [comment]
Closed by #157
