### ISSUE TITLE
Suppress Alumni Email Form

### ISSUE THREAD

**Issue by joe-studer-18** [joe-studer-18/mst-ka-site#172]
We should be able to suppress our "sign up for our newsletter" pop up on the alumni tab based on some criteria (ideally if they've already signed up - but maybe we can limit it to only show on their first visit?)

**Comment by jaredwhanisch** [comment]
@joe-studer-18 

Good thinking, we could possibly utilize local storage to set a flag when a user clicks the signup button to submit their email. The downside is if the user switched browsers or cleared their storage then it would come back up. What do you think?

Also when we are processing the emails on the backend in #171, could we also check if there is an existing entry and remove it if there is?

**Comment by joe-studer-18** [comment]
Checking for that existing entry would still need us to know their email in local storage right? I'm cool w/ the local storage choice, the downsides feel reasonable for the amount of effort it'd take + the QOL improvement we'd get.

**Comment by jaredwhanisch** [comment]
I didn't think so, I originally thought to just save off a Boolean value to check when a user visits the page again after previously submitting their email. But now that I'm thinking about it, I can probably just query the database and check if their email exists and notify them if it does.
