### ISSUE TITLE
Create an "Apply Online" button that is consistent on every page

### ISSUE THREAD

**Issue by joe-studer-18** [joe-studer-18/mst-ka-site#19]
This button should replace the 'settings' button that hangs out on the LHS of every screen from the template, and should act as a secondary link to the apply online form.

**Comment by joe-studer-18** [comment]
@jaredwhanisch @noahklein00 If either of you want this one, it should be a good intro into a bit of Javascript if you'd like to take a whack at it (A lot of the code necessary is already there). If not, I can handle it, just feel free to assign it to yourself if you'd like.

**Comment by noahklein00** [comment]
![applybutton](https://user-images.githubusercontent.com/60161414/85234943-b9cfd480-b3d6-11ea-93a9-07bbc32913ad.png)

**Comment by joe-studer-18** [comment]
I think it may be a little too big/ambiguous on what you're applying for tbh

**Comment by noahklein00** [comment]
What should it say to make it less ambiguous?

**Comment by joe-studer-18** [comment]
I think "Apply Online" would be good. "Apply Now" is also probably ok

**Comment by noahklein00** [comment]
![apply button](https://user-images.githubusercontent.com/60161414/85619310-b54e2a80-b627-11ea-946d-8101302ebeac.png)

**Comment by noahklein00** [comment]
This is what it looks like in relation to the whole page and with the text change.

**Comment by joe-studer-18** [comment]
That looks a lot better! Sorry for the nitpick, but could you change the text color to white? I think it might look cleaner. Feel free to do that in a PR though.

**Comment by joe-studer-18** [comment]
@noahklein00 Looks like the contact us page still has the old gear floating button, can we remove that?

**Comment by noahklein00** [comment]
I think I want to make a change to the button so that way when you scroll all the way down to the bottom the apply button is not covering the bottom footer "hosted on github..." thing. I want to try and keep it in the same place for all the pages but set a lower limit so the button doesn't cover that anymore.

**Comment by joe-studer-18** [comment]
Basically just set display to none when at a certain scroll limit? Sounds good to me.
