### ISSUE TITLE
Fix Page Footer to match Website

### ISSUE THREAD

**Issue by joe-studer-18** [joe-studer-18/mst-ka-site#21]
The page footer is currently just the default from the template. It needs to have updated links, contact info, locations, etc.

**Comment by noahklein00** [comment]
what all do we want included on the footer. What else could it include besides what is on our current website.

**Comment by joe-studer-18** [comment]
Aside from the stuff on the old footer, maybe page navigation? Like a “Quick Links” section. What ideas did you have?

**Comment by noahklein00** [comment]
Back when I was first going through the website and created a list of all the things I thought would be good changes for the new website, one of the biggest things I wanted was to include S&T in our website more. Maybe adding some links to S&T and their pages about greek life would be good?

**Comment by joe-studer-18** [comment]
I like the concept, but maybe at most a single link to the FSL main page? Let’s put it on the back burner for now, I’d like to read up on the legalese of it...can you file that under a separate issue?

**Comment by noahklein00** [comment]
Do we want the social media links in the new footer as well since they are already included in the header?

**Comment by joe-studer-18** [comment]
Yeah I think so. The footer should kinda be the end all for page navigation.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by noahklein00** [comment]
For mobile use I think it might be cool to try and do a drop down list style menu thing instead of having all these blocks awkwardly appear at the bottom of the mobile page. For example, instead of seeing "Contact Us - Beta Alpha ......." with all the info right there, there would be the header "Contact Us - Beta Alpha" and clicking on that would drop down the rest of the information. This would help save a lot of space on the bottom of the mobile website.

**Comment by joe-studer-18** [comment]
Sounds good to me. Can you sketch out what you're thinking on a piece of
paper & post it real quick?

**Comment by noahklein00** [comment]
Currently it looks like this. It is cluttered on the left side and takes up multiple pages of scrolling to go through.
![iphoneOld](https://user-images.githubusercontent.com/60161414/85932237-df098a80-b88f-11ea-8902-343f51e04638.png)
My idea is this, a list of dropdowns
![websiteNewUnopen](https://user-images.githubusercontent.com/60161414/85932249-fe081c80-b88f-11ea-8acf-35e674e5ed44.jpg)
That reveal the information when clicked
![websiteNewOpen](https://user-images.githubusercontent.com/60161414/85932258-0f512900-b890-11ea-9b3b-05f45d2db5ad.jpg)
Again this would be for mobile and small screen

**Comment by joe-studer-18** [comment]
i definitely like the concept. I think it may be better (smaller/lower profile) to make everything below the social media stuff just **Bolded Text >** with a little arrow icon (maybe from favicon?). Then when you click on them it turns into a down-carot and folds out that way. This would replace the thicker button-esque drop downs.

Thoughts?

**Comment by joe-studer-18** [comment]
Also, on a separate note, one thing that's always annoyed me about the website is how we have the same info in multiple locations (like the presidents phone number) but it never gets updated appropriately. Some spots have the new one, some have the old one. 

What are your thoughts on a "globals.js" file which we can use to force functions on specific divs. i.e. anywhere with the presidents phone would now be

```
<div id="presidentPhone" onload="displayPresidentPhone()"  class="..." ></div>
```

The function wouldn't handle stylization, just inserting the inner text.

**Comment by noahklein00** [comment]
Yeah I can try a few different things for the drop down style. The global.js seems like it would  be pretty easy to implement so I say why not

**Comment by joe-studer-18** [comment]
Neat. Can you handle that as part of this issue? It doesn't need to get applied to all instances of the phone number yet, but lets at least start the concept here

**Comment by noahklein00** [comment]
wouldn't it be better for it to have its own issue so then it will just cover everything related to that and we can close this one

**Comment by joe-studer-18** [comment]
Sure. This one's basically done any way.
