### ISSUE TITLE
Clean up/Finalize the 'About' section and related tabs

### ISSUE THREAD

**Issue by jaredwhanisch** [joe-studer-18/mst-ka-site#27]
This issue will finalize the look of views/about.html and all html files contained in views/abouttabs/.

**Comment by joe-studer-18** [comment]
We're shaping up to have a meeting some time next week for BAAA, do you think it'd be possible to have this issue done by say, next Wednesday (Aug 5)? I'd like to have all of our phase 3 goals done by then if possible.

**Comment by jaredwhanisch** [comment]
Yeah I should be able to have something at least better than what's there now.

**Comment by joe-studer-18** [comment]
Any update on how this one is going?

**Comment by jaredwhanisch** [comment]
It's going alright, learning as I go with the css is giving me more trouble than I hoped but I'm slowly figuring it out. I have the main about page looking fairly nice. So if you would like to checkout the branch and give it a look you can see the progress so far. I should have the other pages completed this evening hopefully. I don't know if we have an issue yet for optimizing for mobile site-wide, but that might be a good thing to add because I haven't been focusing on that as much as I probably should. But if you would like me to make it more mobile friendly in this PR I can do that as well.

**Comment by joe-studer-18** [comment]
Oh wow I really like what you did with the images on the main page. It definitely doesn't handle mobile well as of now, I'll leave it up to you on how you want to handle that though.

As an aside, can you also make sure the navbar on each about page points to the right pages? It looks like the links may be a little off.
