### ISSUE TITLE
Awards

### ISSUE THREAD

**Issue by joe-studer-18** [joe-studer-18/mst-ka-site#54]
This page seems to have some pretty rough css still. I think we should view "About" as our gold standard, and reuse the css/styles from that page & its subpages.

**Comment by noahklein00** [comment]
I'm gonna see if someone in the house with a nice camera and a little know-how can take a panoramic of the library and all of our awards for the header picture on the main awards page.

**Comment by joe-studer-18** [comment]
That'd work. Fwiw I think most phones have a panorama options that could work.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by joe-studer-18** [comment]
Lets move the new images to Issue #59 & close this issue
