### ISSUE TITLE
Replacing weird/old pictures across the website

### ISSUE THREAD

**Issue by noahklein00** [joe-studer-18/mst-ka-site#59]
Many of the photos used on the website are old or just of random people. I want to work with someone in house that can go around and take a bunch of photos of newer and more relevant stuff. This will probably involve going through the historian's drive of photos as well to find enough.

**Comment by joe-studer-18** [comment]
Probably a good idea, I'm all for it

**Comment by jaredwhanisch** [comment]
closed by #157
