### ISSUE TITLE
Fix Issues with Apply Online Button @ Bottom Scroll

### ISSUE THREAD

**Issue by joe-studer-18** [joe-studer-18/mst-ka-site#62]
"I think I want to make a change to the button so that way when you scroll all the way down to the bottom the apply button is not covering the bottom footer "hosted on github..." thing. I want to try and keep it in the same place for all the pages but set a lower limit so the button doesn't cover that anymore." - Klein

**Comment by jaredwhanisch** [comment]
Fixed by #158
