### ISSUE TITLE
Increase Mobile Efficiency

### ISSUE THREAD

**Issue by joe-studer-18** [joe-studer-18/mst-ka-site#67]
Follow these [insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fmst-ka.firebaseapp.com%2F&hl=en&tab=mobile) (when reasonable) to improve page speed results on mobile, with a baseline score of 71/100 (goal of 90+).

**Comment by noahklein00** [comment]
I am looking through the unused css on the insights page and in the chrome developer console stuff. I don't know what I should be ok to remove and what I need to keep. It only shows you one page at a time and I am using grep to search for classes, etc. that match in more than just main.css. Is this good enough to delete something, or what should I be looking for. I don't want to delete something important and I don't know how to check what it is affecting.
