### ISSUE TITLE
Migrate to AngularJs

### ISSUE THREAD

**Issue by joe-studer-18** [joe-studer-18/mst-ka-site#85]
Migrating to angular should allow us to template some of our more common components (navbar, apply button, footer, etc), and severely cut down on unecessary LOC. This should make the website considerably easier to maintain, update, and maybe even more fun to work on.

**Comment by jaredwhanisch** [comment]
Oops we migrated to React instead ¯\\\_(ツ)_/¯ 

closed by #158
